set(PANEL_H "${SOURCE_DIR}/src/ui/PerformancePanel.h")
set(PANEL_CPP "${SOURCE_DIR}/src/ui/PerformancePanel.cpp")
set(EDITOR_CPP "${SOURCE_DIR}/src/plugin/PluginEditor.cpp")
foreach(FILE IN ITEMS "${PANEL_H}" "${PANEL_CPP}" "${EDITOR_CPP}")
    if(NOT EXISTS "${FILE}")
        message(FATAL_ERROR "Required live-revoice source missing: ${FILE}")
    endif()
endforeach()
file(READ "${PANEL_H}" HEADER)
file(READ "${PANEL_CPP}" PANEL)
file(READ "${EDITOR_CPP}" EDITOR)

macro(require_text HAYSTACK NEEDLE)
    string(FIND "${${HAYSTACK}}" "${NEEDLE}" FOUND)
    if(FOUND EQUAL -1)
        message(FATAL_ERROR "Live-revoice persistence/UI contract missing: ${NEEDLE}")
    endif()
endmacro()

require_text(HEADER "onLiveRevoiceChanged")
require_text(HEADER "setLiveRevoice")
require_text(PANEL "live-revoice-toggle")
require_text(PANEL "onLiveRevoiceChanged")
require_text(EDITOR "setLiveRevoice(p.getHarmonyState().getLiveRevoice())")
require_text(EDITOR "setLiveRevoice(preset.harmony.getLiveRevoice())")
require_text(EDITOR "getHarmonyState().setLiveRevoice")
